minimized lines for linter

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,8 +6,8 @@ on:
   workflow_dispatch:
 
 jobs:
-  lets-cache:
-    name: lets-cache # By: Earth, Wind & TinyGrad
+  lets-cache: # By: Earth, Wind & TinyGrad
+    name: Cache Python Dependencies
     runs-on: ubuntu-latest
     timeout-minutes: 20
     steps:
@@ -25,8 +25,8 @@ jobs:
       run: |
         python -m venv .venv
         source .venv/bin/activate
+        python -m pip install --upgrade pip
         pip install -e '.[testing,linting]' --extra-index-url https://download.pytorch.org/whl/cpu
-
 
   linter:
     name: Linters
@@ -49,18 +49,14 @@ jobs:
         python -m venv .venv
         source .venv/bin/activate
         pip install -e '.[testing,linting]' --extra-index-url https://download.pytorch.org/whl/cpu
-    - name: Lint with pylint
-      run: python -m venv .venv && source .venv/bin/activate && python -m pylint --disable=all -e W0311 --jobs=0 --indent-string='  ' **/*.py
-    - name: Lint with flake8
-      run: python -m venv .venv && source .venv/bin/activate && flake8 tinygrad/ --indent-size=2 --select=F,E112,E113,E203,E304,E502,E702,E703,E71,E72,E731,W191,W6 --statistics -j4
-    - name: Lint tinygrad with pylint
-      run: python -m venv .venv && source .venv/bin/activate && pylint tinygrad/
-    - name: Run mypy
-      run: python -m venv .venv && source .venv/bin/activate && mypy tinygrad/ --ignore-missing-imports --check-untyped-defs --explicit-package-bases --warn-unreachable
-    - name: Install SLOCCount
-      run: sudo apt-get install sloccount
-    - name: Check <5000 lines
-      run: sloccount tinygrad test examples extra; if [ $(sloccount tinygrad | sed -n 's/.*Total Physical Source Lines of Code (SLOC)[ ]*= \([^ ]*\).*/\1/p' | tr -d ',') -gt 5000 ]; then exit 1; fi
+    - run: |
+        python -m venv .venv && source .venv/bin/activate
+        echo "Spaces... Not tabs!" && python -m pylint --disable=all -e W0311 --jobs=0 --indent-string='  ' **/*.py
+        echo "Lint tinygrad" && pylint tinygrad/
+        echo "Flake8 tinygrad" && flake8 tinygrad/ --indent-size=2 --select=F,E112,E113,E203,E304,E502,E702,E703,E71,E72,E731,W191,W6 --statistics -j4
+        echo "mypy" && mypy tinygrad/ --ignore-missing-imports --check-untyped-defs --explicit-package-bases --warn-unreachable
+        echo "Check <5000 lines" && sudo apt-get install sloccount && sloccount tinygrad test examples extra; if [ $(sloccount tinygrad | sed -n 's/.*Total Physical Source Lines of Code (SLOC)[ ]*= \([^ ]*\).*/\1/p' | tr -d ',') -gt 5000 ]; then exit 1; fi
+
 # whai u do this to me? :(
 #  testcpu:
 #    name: CPU Tests
